### PR TITLE
Migrate to Java 8 and latest Maven 3.8.6

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by karianna** [comment]
@Theoderich - Feel free to reject this if it is overreach :-).  I also did locally bump up to Java 11 and then 17 and they both work fine.

**Comment by lreimer** [comment]
Hey @karianna , how urgent is the PR? @Theoderich is currently on vacation.

**Comment by karianna** [comment]
@lreimer not urgent at all.  We were just using this plugin internally and I figured we should give something back (if it makes sense) :-).

**Comment by karianna** [comment]
@lreimer - Updated it to latest again :-)

**Comment by Theoderich** [comment]
Sorry for the late answer, I was on an extended vacation for the last couple of months.

Thank for for the cleanup and dependency upgrades. I will merge them right away.
Glad to hear you use&like the plugin :)

**Pull request merged**
